// https://leetcode.com/problems/find-the-difference/description/
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

pub fn find_the_difference(s: String, t: String) -> char {
    if s.len() == 0 {
        return t.chars().next().unwrap();
    }

    let mut t = String::from(t);
    for i in s.chars() {
        for (idx, j) in t.chars().enumerate() {
            if i == j {
                t.remove(idx);
                break;
            }
        }
    }

    t.chars().next().unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn example_1() {
        assert_eq!(
            find_the_difference(String::from("abcd"), String::from("abcde")),
            'e'
        );
    }

    #[test]
    fn example_2() {
        assert_eq!(
            find_the_difference(String::from(""), String::from("y")),
            'y'
        );
    }
}
